# Makefile.in generated by automake 1.16.1 from Makefile.am.
# examples/eigenproblems/eigenproblems_ex2/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/libmesh
pkgincludedir = $(includedir)/libmesh
pkglibdir = $(libdir)/libmesh
pkglibexecdir = $(libexecdir)/libmesh
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
target_triplet = x86_64-pc-linux-gnu
check_PROGRAMS = $(am__EXEEXT_1) $(am__EXEEXT_2) $(am__EXEEXT_3) \
	$(am__EXEEXT_4) $(am__EXEEXT_5)
am__append_3 = femvib_ep-ex2
#am__append_4 = example-prof
#am__append_5 = example-oprof
subdir = /home/acooksy/FEMvib/
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps =  \
	$(top_srcdir)/m4/autoconf-submodule/acsm_code_coverage.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_compiler_control_args.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_cxx_compiler_standard.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_mpi.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_scrape_petsc_configure.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_summarize_env.m4 \
	$(top_srcdir)/m4/autoconf-submodule/acsm_test_sanitize_flags.m4 \
	$(top_srcdir)/m4/autoconf-submodule/ax_cxx_compile_stdcxx.m4 \
	$(top_srcdir)/m4/autoconf-submodule/ax_prefix_config_h.m4 \
	$(top_srcdir)/m4/autoconf-submodule/ax_split_version.m4 \
	$(top_srcdir)/m4/autoconf-submodule/ax_subdirs_configure.m4 \
	$(top_srcdir)/m4/ac_cxx_rtti.m4 \
	$(top_srcdir)/m4/acsm_cxx_tests.m4 \
	$(top_srcdir)/m4/all_static.m4 \
	$(top_srcdir)/m4/ax_boost_base.m4 \
	$(top_srcdir)/m4/ax_check_compile_flag.m4 \
	$(top_srcdir)/m4/ax_compiler_vendor.m4 \
	$(top_srcdir)/m4/ax_gcc_archflag.m4 \
	$(top_srcdir)/m4/ax_gcc_x86_cpuid.m4 \
	$(top_srcdir)/m4/ax_openmp.m4 $(top_srcdir)/m4/ax_pthread.m4 \
	$(top_srcdir)/m4/ax_tls.m4 $(top_srcdir)/m4/backtrace.m4 \
	$(top_srcdir)/m4/boost.m4 $(top_srcdir)/m4/capnproto.m4 \
	$(top_srcdir)/m4/compiler.m4 \
	$(top_srcdir)/m4/config_summary.m4 $(top_srcdir)/m4/cppunit.m4 \
	$(top_srcdir)/m4/curl.m4 $(top_srcdir)/m4/cxx17.m4 \
	$(top_srcdir)/m4/demangle.m4 $(top_srcdir)/m4/dlopen.m4 \
	$(top_srcdir)/m4/eigen.m4 $(top_srcdir)/m4/errno_test.m4 \
	$(top_srcdir)/m4/exodus.m4 $(top_srcdir)/m4/feexcept.m4 \
	$(top_srcdir)/m4/fparser.m4 $(top_srcdir)/m4/glpk.m4 \
	$(top_srcdir)/m4/gmv.m4 $(top_srcdir)/m4/gz.m4 \
	$(top_srcdir)/m4/hdf5.m4 $(top_srcdir)/m4/laspack.m4 \
	$(top_srcdir)/m4/libhilbert.m4 \
	$(top_srcdir)/m4/libmesh_compiler_features.m4 \
	$(top_srcdir)/m4/libmesh_core_features.m4 \
	$(top_srcdir)/m4/libmesh_metaphysicl.m4 \
	$(top_srcdir)/m4/libmesh_method.m4 \
	$(top_srcdir)/m4/libmesh_optional_packages.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/locale.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/metis.m4 $(top_srcdir)/m4/namespaces.m4 \
	$(top_srcdir)/m4/nanoflann.m4 $(top_srcdir)/m4/nemesis.m4 \
	$(top_srcdir)/m4/netcdf.m4 $(top_srcdir)/m4/nlopt.m4 \
	$(top_srcdir)/m4/parmetis.m4 $(top_srcdir)/m4/petsc.m4 \
	$(top_srcdir)/m4/precision.m4 $(top_srcdir)/m4/qhull.m4 \
	$(top_srcdir)/m4/sfc.m4 $(top_srcdir)/m4/slepc.m4 \
	$(top_srcdir)/m4/sstream.m4 $(top_srcdir)/m4/strstream.m4 \
	$(top_srcdir)/m4/tbb.m4 $(top_srcdir)/m4/tecio.m4 \
	$(top_srcdir)/m4/tecplot.m4 $(top_srcdir)/m4/tetgen.m4 \
	$(top_srcdir)/m4/threads.m4 $(top_srcdir)/m4/triangle.m4 \
	$(top_srcdir)/m4/trilinos.m4 $(top_srcdir)/m4/unordered.m4 \
	$(top_srcdir)/m4/vtk.m4 $(top_srcdir)/m4/xdr.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/libmesh_config.h.tmp
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__EXEEXT_3 = femvib_ep-ex2$(EXEEXT)
#am__EXEEXT_4 = example-prof$(EXEEXT)
#am__EXEEXT_5 = example-oprof$(EXEEXT)
am__example_dbg_SOURCES_DIST = femvib_ep-ex2.C run.sh
am__objects_1 = example_dbg-femvib_ep-ex2.$(OBJEXT)
am__objects_2 = $(am__objects_1)
am_example_dbg_OBJECTS = $(am__objects_2)
example_dbg_OBJECTS = $(am_example_dbg_OBJECTS)
example_dbg_DEPENDENCIES =  \
	$(top_builddir)/libmesh_dbg.la
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
example_dbg_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(example_dbg_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
am__example_devel_SOURCES_DIST = femvib_ep-ex2.C run.sh
am__objects_3 = example_devel-femvib_ep-ex2.$(OBJEXT)
am__objects_4 = $(am__objects_3)
am_example_devel_OBJECTS = $(am__objects_4)
example_devel_OBJECTS = $(am_example_devel_OBJECTS)
example_devel_DEPENDENCIES =  \
	$(top_builddir)/libmesh_devel.la
example_devel_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(example_devel_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
am__example_oprof_SOURCES_DIST = femvib_ep-ex2.C run.sh
am__objects_5 = example_oprof-femvib_ep-ex2.$(OBJEXT)
am__objects_6 = $(am__objects_5)
#am_example_oprof_OBJECTS = $(am__objects_6)
example_oprof_OBJECTS = $(am_example_oprof_OBJECTS)
#example_oprof_DEPENDENCIES =  \
#	$(top_builddir)/libmesh_oprof.la
example_oprof_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(example_oprof_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
am__example_opt_SOURCES_DIST = femvib_ep-ex2.C run.sh
am__objects_7 = femvib_ep-ex2.$(OBJEXT)
am__objects_8 = $(am__objects_7)
am_example_opt_OBJECTS = $(am__objects_8)
example_opt_OBJECTS = $(am_example_opt_OBJECTS)
example_opt_DEPENDENCIES =  \
	$(top_builddir)/libmesh_opt.la
example_opt_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(example_opt_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
am__example_prof_SOURCES_DIST = femvib_ep-ex2.C run.sh
am__objects_9 = 
am__objects_10 = $(am__objects_9)
#am_example_prof_OBJECTS = $(am__objects_10)
example_prof_OBJECTS = $(am_example_prof_OBJECTS)
#example_prof_DEPENDENCIES =  \
#	$(top_builddir)/libmesh_prof.la
example_prof_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(example_prof_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/include. -I/home/acooksy/FEMvib/include. -I/scratch/acooksy/eigen-3.4.0
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/femvib_ep-ex2.Po \
	./$(DEPDIR)/femvib_ep-ex2.Po \
	./$(DEPDIR)/femvib_ep-ex2.Po \
	./$(DEPDIR)/femvib_ep-ex2.Po \
	./$(DEPDIR)/femvib_ep-ex2.Po
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
# SOURCES = $(example_dbg_SOURCES) $(example_devel_SOURCES) \
# 	$(example_oprof_SOURCES) $(example_opt_SOURCES) \
# 	$(example_prof_SOURCES)
SOURCES = $(example_opt_SOURCES) 
DIST_SOURCES = $(am__example_opt_SOURCES_DIST) 
#	$(am__example_dbg_SOURCES_DIST) \
#	$(am__example_devel_SOURCES_DIST) \
#	$(am__example_oprof_SOURCES_DIST) \
#	$(am__example_prof_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(datadir)"
DATA = $(data_DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
am__tty_colors_dummy = \
  mgn= red= grn= lgn= blu= brg= std=; \
  am__color_tests=no
am__tty_colors = { \
  $(am__tty_colors_dummy); \
  if test "X$(AM_COLOR_TESTS)" = Xno; then \
    am__color_tests=no; \
  elif test "X$(AM_COLOR_TESTS)" = Xalways; then \
    am__color_tests=yes; \
  elif test "X$$TERM" != Xdumb && { test -t 1; } 2>/dev/null; then \
    am__color_tests=yes; \
  fi; \
  if test $$am__color_tests = yes; then \
    red='[0;31m'; \
    grn='[0;32m'; \
    lgn='[1;32m'; \
    blu='[1;34m'; \
    mgn='[0;35m'; \
    brg='[1m'; \
    std='[m'; \
  fi; \
}
am__DIST_COMMON = $(srcdir)/Makefile.in \
	$(top_srcdir)/build-aux/depcomp \
	$(top_srcdir)/examples/Make.common
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
ANY_PARANOID_FLAGS = 
ANY_WERROR_FLAG = 
AR = ar
AUTOCONF = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/missing autoconf
AUTOHEADER = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/missing autoheader
AUTOMAKE = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/missing automake-1.16
AWK = gawk
AZTECOO_INCLUDES = 
AZTECOO_LIBS = 
AZTECOO_MAKEFILE_EXPORT = 
BOOST_CPPFLAGS = -I./contrib/boost/include
BOOST_LDFLAGS = -L/lib64
BUILD_ARCH = x86_64-pc-linux-gnu
BUILD_DEVSTATUS = External Release
BUILD_HOST = islands
BUILD_USER = acooksy
BUILD_VERSION = external
BUNZIP2 = bunzip2
BZIP2 = bzip2
CAPNPROTO_INCLUDE = 
CAPNPROTO_LIBRARY = 
CAPNP_BINARY = 
CC = mpicc
CCDEPMODE = depmode=gcc3
CFLAGS = 
CFLAGS_DBG = -g -Wimplicit    -fopenmp
CFLAGS_DEVEL = -O2 -funroll-loops -fstrict-aliasing -g -Wimplicit -funroll-loops -fstrict-aliasing    -fopenmp
CFLAGS_DVL = 
CFLAGS_OPROF = -O2 -funroll-loops -fstrict-aliasing   -g -fno-omit-frame-pointer  -fopenmp
CFLAGS_OPT = -O2 -funroll-loops -fstrict-aliasing    -fopenmp ## ORIG
## CFLAGS_OPT = -g -O2 -funroll-loops -fstrict-aliasing    -fopenmp  ## switch in place of line above to add debugging
CFLAGS_PROF = -O2 -funroll-loops -fstrict-aliasing   -pg  -fopenmp
CPP = mpicc -E
CPPFLAGS = 
CPPFLAGS_DBG = -DDEBUG 
CPPFLAGS_DEVEL =  
CPPFLAGS_OPROF = -DNDEBUG 
CPPFLAGS_OPT = -DNDEBUG 
CPPFLAGS_PROF = -DNDEBUG 
CPPUNIT_CFLAGS = 
CPPUNIT_CONFIG = none
CPPUNIT_LIBS = 
CURL_INCLUDE = 
CURL_LIBRARY = 
CXX = mpicxx -std=gnu++17
CXXCPP = mpicxx -std=gnu++17 -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 

# We might have turned on -Werror and/or paranoid warnings
CXXFLAGS_DBG =  -O0 -felide-constructors -g -pedantic -W -Wall -Wextra -Wno-long-long -Wunused -Wpointer-arith -Wformat -Wparentheses -Woverloaded-virtual    -fopenmp $(ANY_WERROR_FLAG) $(ANY_PARANOID_FLAGS)
CXXFLAGS_DEVEL =  -O2 -felide-constructors -g -pedantic -W -Wall -Wextra -Wno-long-long -Wunused -Wpointer-arith -Wformat -Wparentheses -Wuninitialized -funroll-loops -fstrict-aliasing -Woverloaded-virtual -Wdisabled-optimization    -fopenmp $(ANY_WERROR_FLAG) \
	$(ANY_PARANOID_FLAGS)
CXXFLAGS_DVL = 
CXXFLAGS_OPROF =  -O2 -felide-constructors -funroll-loops -fstrict-aliasing -Wdisabled-optimization   -g -fno-omit-frame-pointer  -fopenmp $(ANY_WERROR_FLAG) \
	$(ANY_PARANOID_FLAGS)
CXXFLAGS_OPT =  -O2 -felide-constructors -funroll-loops -fstrict-aliasing -Wdisabled-optimization    -fopenmp $(ANY_WERROR_FLAG) $(ANY_PARANOID_FLAGS)
CXXFLAGS_PROF =  -O2 -felide-constructors -funroll-loops -fstrict-aliasing -Wdisabled-optimization   -pg  -fopenmp $(ANY_WERROR_FLAG) \
	$(ANY_PARANOID_FLAGS)
CXXSHAREDFLAG = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DOT = 
DOTPATH = 
DOXYGEN = /usr/bin/doxygen
DSYMUTIL = 
DTK_MAKEFILE_EXPORT = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EIGEN_INCLUDE = -I$(top_srcdir)/contrib/eigen/eigen
EXEEXT = 
EXODUS_INCLUDE = -I$(top_srcdir)/contrib/exodusii/v5.22/exodus/cbind/include
EXODUS_NOT_NETCDF4_FLAG = -DNOT_NETCDF4
F77 = mpif77
FC = mpif90
FCFLAGS = -g -O2
FFLAGS = -g -O2 -fopenmp
FGREP = /bin/grep -F
FLIBS = 
FPARSER_INCLUDE = -I$(top_srcdir)/contrib/fparser
FPARSER_LIBRARY = $(EXTERNAL_LIBDIR)/libfparser$(libext)
GCOV_FLAGS = 
GCOV_LDFLAGS = 
GIT_REVISION = external
GLPK_INCLUDE = 
GLPK_LIBRARY = 
GMV_INCLUDE = -I$(top_srcdir)/contrib/gmv
GMV_LIBRARY = $(EXTERNAL_LIBDIR)/libgmv$(libext)
GREP = /bin/grep
GXX_VERSION = gcc7
GZSTREAM_INCLUDE = 
GZSTREAM_LIB = 
HAVE_CXX11 = 1
HAVE_CXX14 = 1
HAVE_CXX17 = 1
HAVE_DOT = NO
HAVE_GCOV_TOOLS = 0
HDF5_CFLAGS = 
HDF5_CPPFLAGS = 
HDF5_CXXLIBS = 
HDF5_DIR = 
HDF5_FLIBS = 
HDF5_LIBS = 
HDF5_PREFIX = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LASPACK_INCLUDE = 
LASPACK_LIB = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBHILBERT_INCLUDE = -I$(top_srcdir)/contrib/libHilbert/include
LIBHILBERT_LIBRARY = $(EXTERNAL_LIBDIR)/libHilbert$(libext)
LIBOBJS = 
LIBS = $(libmesh_optional_LIBS)
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LOCAL_CXX = 
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAINT = #
MAKEINFO = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/missing makeinfo
MANIFEST_TOOL = :
METAPHYSICL_INCLUDE = -I$(top_srcdir)/contrib/metaphysicl/src/numerics/include -I$(top_srcdir)/contrib/metaphysicl/src/core/include -I$(top_srcdir)/contrib/metaphysicl/src/utilities/include
METHOD = 
METHODS = opt
METIS_INCLUDE = -I$(top_srcdir)/contrib/metis/include
METIS_LIB = 
MKDIR_P = /bin/mkdir -p
ML_INCLUDES = 
ML_LIBS = 
ML_MAKEFILE_EXPORT = 
MPCXX = 
MPI_IMPL = CXX-built-in
MPI_INCLUDES = 
MPI_LDFLAGS = 
MPI_LIBS = 
NANOFLANN_INCLUDE = -I$(top_srcdir)/contrib/nanoflann/include
NEMESIS_INCLUDE = -I$(top_srcdir)/contrib/nemesis/v5.22/nemesis
NETCDF_INCLUDE = -I$(top_srcdir)/contrib/netcdf/v4/include
NLOPT_INCLUDE = -I
NLOPT_LIBRARY = -L -lnlopt
NM = /usr/bin/nm -B
NMEDIT = 
NODEPRECATEDFLAG = -Wno-deprecated
NOX_INCLUDES = 
NOX_LIBS = 
NOX_MAKEFILE_EXPORT = 
OBJDUMP = objdump
OBJEXT = o
OPENMP_CFLAGS = -fopenmp
OPENMP_CXXFLAGS = -fopenmp
OPENMP_FFLAGS = -fopenmp
OPROFILE_FLAGS = -g -fno-omit-frame-pointer
OTOOL = 
OTOOL64 = 
PACKAGE = libmesh
PACKAGE_BUGREPORT = https://github.com/libMesh/libmesh/discussions
PACKAGE_NAME = libmesh
PACKAGE_STRING = libmesh 1.7.1
PACKAGE_TARNAME = libmesh
PACKAGE_URL = http://libmesh.github.io
PACKAGE_VERSION = 1.7.1
PARMETIS_INCLUDE = -I$(top_srcdir)/contrib/parmetis/include
PARMETIS_LIB = 
PATH_SEPARATOR = :
PERL = /usr/bin/perl
PETSCARCH = 
PETSCINCLUDEDIRS = -I/scratch/acooksy/petsc/petsc-3.13.6/include -I/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/include -I/scratch/acooksy/petsc/petsc-3.13.6/include -I/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/include
PETSCLINKLIBS = -Wl,-rpath,/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -L/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -Wl,-rpath,/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -L/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lpetsc -lflapack -lfblas -lpthread -lm -lstdc++ -ldl -lmpichfort -lmpich -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lstdc++ -ldl
PETSC_ARCH = arch-linux2-c-debug
PETSC_CC_INCLUDES = -I/scratch/acooksy/petsc/petsc-3.13.6/include -I/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/include
PETSC_DIR = /scratch/acooksy/petsc/petsc-3.13.6
PETSC_FC_INCLUDES = -I/scratch/acooksy/petsc/petsc-3.13.6/include -I/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/include
PKG_CONFIG = no
PROFILING_FLAGS = -pg
PRTDIAG = 
PTHREAD_CC = mpicc
PTHREAD_CFLAGS = -pthread
PTHREAD_LIBS = 
PWD = /scratch/acooksy/libmesh/libmesh-1.7.1
QHULL_LIBS = -lm
RANLIB = ranlib
RPATHFLAG = -Wl,-rpath,
SED = /bin/sed
SET_MAKE = 
SFC_INCLUDE = 
SFC_LIB = 
SHELL = /bin/bash
SLEPC_DIR = /scratch/acooksy/slepc/slepc-3.13.4
SLEPC_INCLUDE = -I/scratch/acooksy/slepc/slepc-3.13.4/include -I/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/include
SLEPC_LIBS = -Wl,-rpath,/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/lib -L/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/lib -lslepc -Wl,-rpath,/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -L/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -Wl,-rpath,/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -L/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lpetsc -lflapack -lfblas -lpthread -lm -lstdc++ -ldl -lmpichfort -lmpich -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lstdc++ -ldl
STRIP = strip
TBB_INCLUDE = 
TBB_LIBRARY = 
TECIO_CPPFLAGS = 
TECIO_INCLUDE = 
TETGEN_INCLUDE = 
TETGEN_LIBRARY = 
TPETRA_INCLUDES = 
TPETRA_LIBS = 
TPETRA_MAKEFILE_EXPORT = 
TRIANGLE_INCLUDE = 
TRIANGLE_LIBRARY = 
TRILINOS_DIR = no
TRILINOS_INCLUDES = 
TRILINOS_LIBS = 
TRILINOS_MAKEFILE_EXPORT = 
VERSION = 1.7.1
VTK_DIR = /usr
VTK_INCLUDE = 
VTK_LIBRARY = 
XZ = xz
YACC = bison -y
YFLAGS = 
abs_builddir = /home/acooksy/FEMvib
abs_srcdir = /home/acooksy/FEMvib
abs_top_builddir = /scratch/acooksy/libmesh/libmesh-1.7.1
abs_top_srcdir = /scratch/acooksy/libmesh/libmesh-1.7.1
ac_ct_AR = ar
ac_ct_CC = mpicc
ac_ct_CXX = 
ac_ct_DUMPBIN = 
ac_ct_F77 = mpif77
ac_ct_FC = mpif90
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
ax_pthread_config = 
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = $(install_dir)
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
enabledeprecated = yes
enablefwdenums = yes
enablelegacyincludepaths = no
enablepetsc = yes
enableuniqueptr = irrelevant
enablewarnings = yes
exec_prefix = ${prefix}
gitquery = /usr/bin/git
have_gcov = 
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /scratch/acooksy/libmesh/libmesh-1.7.1/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
libmesh_CFLAGS =  
libmesh_CPPFLAGS = 
libmesh_CXXFLAGS =  
libmesh_LDFLAGS = 
libmesh_contrib_INCLUDES = -I$(top_srcdir)/contrib/metaphysicl/src/numerics/include -I$(top_srcdir)/contrib/metaphysicl/src/core/include -I$(top_srcdir)/contrib/metaphysicl/src/utilities/include -I$(top_srcdir)/contrib/nanoflann/include -I$(top_srcdir)/contrib/fparser -I$(top_srcdir)/contrib/libHilbert/include -I$(top_srcdir)/contrib/nemesis/v5.22/nemesis -I$(top_srcdir)/contrib/exodusii/v5.22/exodus/cbind/include -I$(top_srcdir)/contrib/netcdf/v4/include -I$(top_srcdir)/contrib/eigen/eigen -I$(top_srcdir)/contrib/gmv -I$(top_srcdir)/contrib/qhull/qhull/src -I$(top_srcdir)/contrib/qhull/qhull/src/libqhullcpp -I$(top_srcdir)/contrib/parmetis/include -I$(top_srcdir)/contrib/metis/include -I$(top_srcdir)/contrib/boost/include -I$(top_builddir)/contrib/timpi/src/utilities/include -I$(top_srcdir)/contrib/timpi/src/utilities/include -I$(top_srcdir)/contrib/timpi/src/parallel/include -I$(top_srcdir)/contrib/timpi/src/algorithms/include 
libmesh_installed_LIBS = 
libmesh_optional_INCLUDES = -pthread -I/scratch/acooksy/slepc/slepc-3.13.4/include -I/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/include -I/scratch/acooksy/petsc/petsc-3.13.6/include -I/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/include
libmesh_optional_LIBS = -Wl,-rpath,/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/lib -L/scratch/acooksy/slepc/slepc-3.13.4/arch-linux2-c-debug/lib -Wl,-rpath,/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -L/scratch/acooksy/petsc/petsc-3.13.6/arch-linux2-c-debug/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -lslepc -lpetsc -lflapack -lfblas -lpthread -lmpichfort -lmpich -lgfortran -lm -lgcc_s -lquadmath -lstdc++ -ldl
libmesh_pkgconfig_requires = netcdf >= 4.2 
libmesh_precision_LIBS = 
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
petscmajor = 3
petscmajorminor = 3.13.x
petscminor = 13
petscversion = 3.13.6
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
subdirs =  contrib/netcdf/v4 contrib/timpi
subdirs_extra =  contrib/metaphysicl
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_build_prefix = /scratch/acooksy/libmesh/libmesh-1.7.1
top_builddir = /scratch/acooksy/libmesh/libmesh-1.7.1
top_srcdir = /scratch/acooksy/libmesh/libmesh-1.7.1
vtkbuild = 
vtkmajor = 
vtkversion = 
example_name = eigenproblems_ex2
install_dir = /home/acooksy/FEMvib
data = femvib_ep-ex2.C run.sh
sources = $(data) run.sh

######################################################################
#
# how to make documentation
#
CLEANFILES = out.e /home/acooksy/FEMvib/femvib.html stdout.log

# conditionally enable this test
check_SCRIPTS = run.sh

######################################################################
#
# Common environment for all examples
#
# This file is included by *every* example.  If we are careful, common
# rules like 'make doc' or 'make run' can be defined here, once and
# for all.
#
AUTOMAKE_OPTIONS = subdir-objects
AM_CPPFLAGS = $(libmesh_optional_INCLUDES) -I$(top_builddir)/include $(libmesh_contrib_INCLUDES)
AM_CFLAGS = $(libmesh_CFLAGS)
AM_CXXFLAGS = $(libmesh_CXXFLAGS)
AM_LDFLAGS = $(libmesh_LDFLAGS)
examples_source_path = $(top_srcdir)/examples
examples_install_path = $(prefix)/examples
data_DATA = $(data) $(top_builddir)/contrib/utils/Makefile
# example_dbg_SOURCES = $(sources)
# example_dbg_CPPFLAGS = $(CPPFLAGS_DBG) $(AM_CPPFLAGS)
# example_dbg_CXXFLAGS = $(CXXFLAGS_DBG)
# example_dbg_LDADD = $(top_builddir)/libmesh_dbg.la
# example_devel_SOURCES = $(sources)
# example_devel_CPPFLAGS = $(CPPFLAGS_DEVEL) $(AM_CPPFLAGS)
# example_devel_CXXFLAGS = $(CXXFLAGS_DEVEL)
# example_devel_LDADD = $(top_builddir)/libmesh_devel.la
example_opt_SOURCES = $(sources)
example_opt_CPPFLAGS = $(CPPFLAGS_OPT) $(AM_CPPFLAGS)
example_opt_CXXFLAGS = $(CXXFLAGS_OPT)
example_opt_LDADD = $(top_builddir)/libmesh_opt.la
#example_prof_SOURCES = $(sources)
#example_prof_CPPFLAGS = $(CPPFLAGS_PROF) $(AM_CPPFLAGS)
#example_prof_CXXFLAGS = $(CXXFLAGS_PROF)
#example_prof_LDADD = $(top_builddir)/libmesh_prof.la
#example_oprof_SOURCES = $(sources)
#example_oprof_CPPFLAGS = $(CPPFLAGS_OPROF) $(AM_CPPFLAGS)
#example_oprof_CXXFLAGS = $(CXXFLAGS_OPROF)
#example_oprof_LDADD = $(top_builddir)/libmesh_oprof.la
#DOC_PROGRAM = example-devel

######################################################################
#
# Choose a flavor to run when making documentation
#
DOC_PROGRAM = femvib
DOC_METHOD = opt

######################################################################
#
# Running the tests
#
TESTS_ENVIRONMENT = LIBMESH_DIR=$(abs_top_srcdir); export LIBMESH_DIR; \
	METHODS="$(METHODS)"; export METHODS; petscmajor=3 \
	petscminor=13
TESTS = $(check_SCRIPTS)
all: all-am

.SUFFIXES:
.SUFFIXES: .C .lo .o .obj
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am $(top_srcdir)/examples/Make.common $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu /home/acooksy/FEMvib/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu /home/acooksy/FEMvib/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles);; \
	esac;
$(top_srcdir)/examples/Make.common $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

clean-checkPROGRAMS:
	@list='$(check_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

# example-dbg$(EXEEXT): $(example_dbg_OBJECTS) $(example_dbg_DEPENDENCIES) $(EXTRA_example_dbg_DEPENDENCIES) 
# 	@rm -f example-dbg$(EXEEXT)
# 	$(AM_V_CXXLD)$(example_dbg_LINK) $(example_dbg_OBJECTS) $(example_dbg_LDADD) $(LIBS)

# example-devel$(EXEEXT): $(example_devel_OBJECTS) $(example_devel_DEPENDENCIES) $(EXTRA_example_devel_DEPENDENCIES) 
# 	@rm -f example-devel$(EXEEXT)
# 	$(AM_V_CXXLD)$(example_devel_LINK) $(example_devel_OBJECTS) $(example_devel_LDADD) $(LIBS)

femvib_ep-ex2$(EXEEXT): $(example_opt_OBJECTS) $(example_opt_DEPENDENCIES) $(EXTRA_example_opt_DEPENDENCIES) 
	@rm -f femvib_ep-ex2$(EXEEXT)
	$(AM_V_CXXLD)$(example_opt_LINK) $(example_opt_OBJECTS) $(example_opt_LDADD) $(LIBS)


mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

# include ./$(DEPDIR)/example_dbg-femvib_ep-ex2.Po # am--include-marker
# include ./$(DEPDIR)/example_devel-femvib_ep-ex2.Po # am--include-marker
# include ./$(DEPDIR)/example_oprof-femvib_ep-ex2.Po # am--include-marker
include ./$(DEPDIR)/femvib_ep-ex2.Po # am--include-marker
# include ./$(DEPDIR)/example_prof-femvib_ep-ex2.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.C.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.C.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.C.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

# example_dbg-femvib_ep-ex2.o: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_dbg_CPPFLAGS) $(CPPFLAGS) $(example_dbg_CXXFLAGS) $(CXXFLAGS) -MT example_dbg-femvib_ep-ex2.o -MD -MP -MF $(DEPDIR)/example_dbg-femvib_ep-ex2.Tpo -c -o example_dbg-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_dbg-femvib_ep-ex2.Tpo $(DEPDIR)/example_dbg-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_dbg-femvib_ep-ex2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_dbg_CPPFLAGS) $(CPPFLAGS) $(example_dbg_CXXFLAGS) $(CXXFLAGS) -c -o example_dbg-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C

# example_dbg-femvib_ep-ex2.obj: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_dbg_CPPFLAGS) $(CPPFLAGS) $(example_dbg_CXXFLAGS) $(CXXFLAGS) -MT example_dbg-femvib_ep-ex2.obj -MD -MP -MF $(DEPDIR)/example_dbg-femvib_ep-ex2.Tpo -c -o example_dbg-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_dbg-femvib_ep-ex2.Tpo $(DEPDIR)/example_dbg-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_dbg-femvib_ep-ex2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_dbg_CPPFLAGS) $(CPPFLAGS) $(example_dbg_CXXFLAGS) $(CXXFLAGS) -c -o example_dbg-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`

# example_devel-femvib_ep-ex2.o: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_devel_CPPFLAGS) $(CPPFLAGS) $(example_devel_CXXFLAGS) $(CXXFLAGS) -MT femvib_ep-ex2.o -MD -MP -MF $(DEPDIR)/femvib_ep-ex2.Tpo -c -o femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/femvib_ep-ex2.Tpo $(DEPDIR)/femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='femvib_ep-ex2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_devel_CPPFLAGS) $(CPPFLAGS) $(example_devel_CXXFLAGS) $(CXXFLAGS) -c -o femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C

femvib_ep-ex2.obj: femvib_ep-ex2.C
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_devel_CPPFLAGS) $(CPPFLAGS) $(example_devel_CXXFLAGS) $(CXXFLAGS) -MT femvib_ep-ex2.obj -MD -MP -MF $(DEPDIR)/femvib_ep-ex2.Tpo -c -o femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/femvib_ep-ex2.Tpo $(DEPDIR)/femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_devel-femvib_ep-ex2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_devel_CPPFLAGS) $(CPPFLAGS) $(example_devel_CXXFLAGS) $(CXXFLAGS) -c -o example_devel-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`

# example_oprof-femvib_ep-ex2.o: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_oprof_CPPFLAGS) $(CPPFLAGS) $(example_oprof_CXXFLAGS) $(CXXFLAGS) -MT example_oprof-femvib_ep-ex2.o -MD -MP -MF $(DEPDIR)/example_oprof-femvib_ep-ex2.Tpo -c -o example_oprof-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_oprof-femvib_ep-ex2.Tpo $(DEPDIR)/example_oprof-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_oprof-femvib_ep-ex2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_oprof_CPPFLAGS) $(CPPFLAGS) $(example_oprof_CXXFLAGS) $(CXXFLAGS) -c -o example_oprof-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C

# example_oprof-femvib_ep-ex2.obj: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_oprof_CPPFLAGS) $(CPPFLAGS) $(example_oprof_CXXFLAGS) $(CXXFLAGS) -MT example_oprof-femvib_ep-ex2.obj -MD -MP -MF $(DEPDIR)/example_oprof-femvib_ep-ex2.Tpo -c -o example_oprof-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_oprof-femvib_ep-ex2.Tpo $(DEPDIR)/example_oprof-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_oprof-femvib_ep-ex2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_oprof_CPPFLAGS) $(CPPFLAGS) $(example_oprof_CXXFLAGS) $(CXXFLAGS) -c -o example_oprof-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`

femvib_ep-ex2.o: femvib_ep-ex2.C
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_opt_CPPFLAGS) $(CPPFLAGS) $(example_opt_CXXFLAGS) $(CXXFLAGS) -MT femvib_ep-ex2.o -MD -MP -MF $(DEPDIR)/femvib_ep-ex2.Tpo -c -o femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C
	$(AM_V_at)$(am__mv) $(DEPDIR)/femvib_ep-ex2.Tpo $(DEPDIR)/femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='femvib_ep-ex2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_opt_CPPFLAGS) $(CPPFLAGS) $(example_opt_CXXFLAGS) $(CXXFLAGS) -c -o femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C

# femvib_ep-ex2.obj: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_opt_CPPFLAGS) $(CPPFLAGS) $(example_opt_CXXFLAGS) $(CXXFLAGS) -MT femvib_ep-ex2.obj -MD -MP -MF $(DEPDIR)/femvib_ep-ex2.Tpo -c -o femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/femvib_ep-ex2.Tpo $(DEPDIR)/femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='femvib_ep-ex2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_opt_CPPFLAGS) $(CPPFLAGS) $(example_opt_CXXFLAGS) $(CXXFLAGS) -c -o femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`

# example_prof-femvib_ep-ex2.o: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_prof_CPPFLAGS) $(CPPFLAGS) $(example_prof_CXXFLAGS) $(CXXFLAGS) -MT example_prof-femvib_ep-ex2.o -MD -MP -MF $(DEPDIR)/example_prof-femvib_ep-ex2.Tpo -c -o example_prof-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_prof-femvib_ep-ex2.Tpo $(DEPDIR)/example_prof-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_prof-femvib_ep-ex2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_prof_CPPFLAGS) $(CPPFLAGS) $(example_prof_CXXFLAGS) $(CXXFLAGS) -c -o example_prof-femvib_ep-ex2.o `test -f 'femvib_ep-ex2.C' || echo '$(srcdir)/'`femvib_ep-ex2.C

# example_prof-femvib_ep-ex2.obj: femvib_ep-ex2.C
# 	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_prof_CPPFLAGS) $(CPPFLAGS) $(example_prof_CXXFLAGS) $(CXXFLAGS) -MT example_prof-femvib_ep-ex2.obj -MD -MP -MF $(DEPDIR)/example_prof-femvib_ep-ex2.Tpo -c -o example_prof-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`
# 	$(AM_V_at)$(am__mv) $(DEPDIR)/example_prof-femvib_ep-ex2.Tpo $(DEPDIR)/example_prof-femvib_ep-ex2.Po
#	$(AM_V_CXX)source='femvib_ep-ex2.C' object='example_prof-femvib_ep-ex2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(example_prof_CPPFLAGS) $(CPPFLAGS) $(example_prof_CXXFLAGS) $(CXXFLAGS) -c -o example_prof-femvib_ep-ex2.obj `if test -f 'femvib_ep-ex2.C'; then $(CYGPATH_W) 'femvib_ep-ex2.C'; else $(CYGPATH_W) '$(srcdir)/femvib_ep-ex2.C'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
install-dataDATA: $(data_DATA)
	@$(NORMAL_INSTALL)
	@list='$(data_DATA)'; test -n "$(datadir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(datadir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(datadir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(datadir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(datadir)" || exit $$?; \
	done

uninstall-dataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(data_DATA)'; test -n "$(datadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(datadir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
	srcdir=$(srcdir); export srcdir; \
	list=' $(TESTS) '; \
	$(am__tty_colors); \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst $(AM_TESTS_FD_REDIRECT); then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xpass=`expr $$xpass + 1`; \
		failed=`expr $$failed + 1`; \
		col=$$red; res=XPASS; \
	      ;; \
	      *) \
		col=$$grn; res=PASS; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xfail=`expr $$xfail + 1`; \
		col=$$lgn; res=XFAIL; \
	      ;; \
	      *) \
		failed=`expr $$failed + 1`; \
		col=$$red; res=FAIL; \
	      ;; \
	      esac; \
	    else \
	      skip=`expr $$skip + 1`; \
	      col=$$blu; res=SKIP; \
	    fi; \
	    echo "$${col}$$res$${std}: $$tst"; \
	  done; \
	  if test "$$all" -eq 1; then \
	    tests="test"; \
	    All=""; \
	  else \
	    tests="tests"; \
	    All="All "; \
	  fi; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="$$All$$all $$tests passed"; \
	    else \
	      if test "$$xfail" -eq 1; then failures=failure; else failures=failures; fi; \
	      banner="$$All$$all $$tests behaved as expected ($$xfail expected $$failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all $$tests failed"; \
	    else \
	      if test "$$xpass" -eq 1; then passes=pass; else passes=passes; fi; \
	      banner="$$failed of $$all $$tests did not behave as expected ($$xpass unexpected $$passes)"; \
	    fi; \
	  fi; \
	  dashes="$$banner"; \
	  skipped=""; \
	  if test "$$skip" -ne 0; then \
	    if test "$$skip" -eq 1; then \
	      skipped="($$skip test was not run)"; \
	    else \
	      skipped="($$skip tests were not run)"; \
	    fi; \
	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$skipped"; \
	  fi; \
	  report=""; \
	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
	    report="Please report to $(PACKAGE_BUGREPORT)"; \
	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$report"; \
	  fi; \
	  dashes=`echo "$$dashes" | sed s/./=/g`; \
	  if test "$$failed" -eq 0; then \
	    col="$$grn"; \
	  else \
	    col="$$red"; \
	  fi; \
	  echo "$${col}$$dashes$${std}"; \
	  echo "$${col}$$banner$${std}"; \
	  test -z "$$skipped" || echo "$${col}$$skipped$${std}"; \
	  test -z "$$report" || echo "$${col}$$report$${std}"; \
	  echo "$${col}$$dashes$${std}"; \
	  test "$$failed" -eq 0; \
	else :; fi

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS) $(check_SCRIPTS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(datadir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-checkPROGRAMS clean-generic clean-libtool \
	mostlyclean-am

distclean: distclean-am
# 		-rm -f ./$(DEPDIR)/example_dbg-femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_devel-femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_oprof-femvib_ep-ex2.Po
	-rm -f ./$(DEPDIR)/femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_prof-femvib_ep-ex2.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html-am:

info: info-am

info-am:

install-data-am: install-dataDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
# 		-rm -f ./$(DEPDIR)/example_dbg-femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_devel-femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_oprof-femvib_ep-ex2.Po
	-rm -f ./$(DEPDIR)/femvib_ep-ex2.Po
# 	-rm -f ./$(DEPDIR)/example_prof-femvib_ep-ex2.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-dataDATA

.MAKE: check-am install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles check check-TESTS \
	check-am clean clean-checkPROGRAMS clean-generic clean-libtool \
	cscopelist-am ctags ctags-am distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dataDATA install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-dataDATA

.PRECIOUS: Makefile


# Convenience method: 'make run'
run: $(check_PROGRAMS)
	LIBMESH_DIR=$(abs_top_srcdir) METHODS="$(METHODS)" $(srcdir)/$(check_SCRIPTS)
##	echo '$(check_PROGRAMS)'
##	echo 'LIBMESH_DIR=$(abs_top_srcdir) '
##	echo 'METHODS="$(METHODS)"'
##	echo '$(srcdir)/$(check_SCRIPTS)'
doc: /home/acooksy/FEMvib/femvib.html
html: /home/acooksy/FEMvib/femvib.html
/home/acooksy/FEMvib/femvib.html: $(DOC_PROGRAM) \
                        $(top_srcdir)/contrib/bin/ex2html.sh \
                       Makefile
	$(MAKE) METHODS=$(DOC_METHOD) -s run > stdout.log
	$(AM_V_GEN) PATH=$(abs_top_srcdir)/contrib/bin:$(PATH) \
	  ex2html.sh /home/acooksy/FEMvib/femvib $(abs_srcdir)

# Local Variables:
# mode: makefile
# End:

##############################################
# include common example environment

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
